Disables EclipseLink "fetch groups" weaving.
This change was prompted by an error message that appeared in the
nightly regression tests for Feb. 16th 2011:

----------------------------------------------------------------------
19:30:28.686 [Close Session Factory] WARN 
o.e.j.c.core.persistence.Hibernator - Could not shut down lock
manager.
org.eclipse.persistence.exceptions.DescriptorException: 
Exception Description: The method [getId] on the object
[org.eclipse.jubula.client.core.persistence.locking.ApplicationPO]
triggered an exception.
Internal Exception: java.lang.reflect.InvocationTargetException
Target Invocation Exception: java.lang.NoSuchMethodError:
org.eclipse.persistence.queries.FetchGroup.containsAttributeInternal(Ljava/lang/String;)Z
Mapping:
org.eclipse.persistence.mappings.DirectToFieldMapping[id-->APPLICATION.ID]
Descriptor:
RelationalDescriptor(org.eclipse.jubula.client.core.persistence.locking.ApplicationPO
--> [DatabaseTable(APPLICATION)])
	at
org.eclipse.persistence.exceptions.DescriptorException.targetInvocationWhileGettingValueThruMethodAccessor(DescriptorException.java:1684)
~[na:na]
	at
org.eclipse.persistence.internal.descriptors.MethodAttributeAccessor.getAttributeValueFromObject(MethodAttributeAccessor.java:89)
~[na:na]
	at
org.eclipse.persistence.internal.descriptors.MethodAttributeAccessor.getAttributeValueFromObject(MethodAttributeAccessor.java:61)
~[na:na]
	at
org.eclipse.persistence.mappings.DatabaseMapping.getAttributeValueFromObject(DatabaseMapping.java:523)
~[na:na]
	at
org.eclipse.persistence.mappings.foundation.AbstractDirectMapping.valueFromObject(AbstractDirectMapping.java:1226)
~[na:na]
	at
org.eclipse.persistence.internal.descriptors.ObjectBuilder.extractPrimaryKeyFromObject(ObjectBuilder.java:2265)
~[na:na]
	at
org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerExistingObject(UnitOfWorkImpl.java:3864)
~[na:na]
	at
org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.registerExistingObject(UnitOfWorkImpl.java:3826)
~[na:na]
	at
org.eclipse.persistence.internal.sessions.UnitOfWorkImpl.getReference(UnitOfWorkImpl.java:5780)
~[na:na]
	at
org.eclipse.persistence.internal.jpa.EntityManagerImpl.getReference(EntityManagerImpl.java:1236)
~[na:na]
	at
org.eclipse.jubula.client.core.persistence.locking.LockManager.removeApp(LockManager.java:286)
~[na:na]
	at
org.eclipse.jubula.client.core.persistence.locking.LockManager.access$3(LockManager.java:282)
~[na:na]
	at
org.eclipse.jubula.client.core.persistence.locking.LockManager$5.run(LockManager.java:270)
~[na:na]
	at
org.eclipse.jubula.client.core.persistence.locking.LockManager.runInSession(LockManager.java:139)
~[na:na]
	at
org.eclipse.jubula.client.core.persistence.locking.LockManager.dispose(LockManager.java:267)
~[na:na]
	at
org.eclipse.jubula.client.core.persistence.Hibernator$1.run(Hibernator.java:81)
~[na:na]
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.GeneratedMethodAccessor249.invoke(Unknown Source)
~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
~[na:1.6.0_18]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.6.0_18]
	at
org.eclipse.persistence.internal.descriptors.MethodAttributeAccessor.getAttributeValueFromObject(MethodAttributeAccessor.java:82)
~[na:na]
	... 14 common frames omitted
Caused by: java.lang.NoSuchMethodError:
org.eclipse.persistence.queries.FetchGroup.containsAttributeInternal(Ljava/lang/String;)Z
	at
org.eclipse.jubula.client.core.persistence.locking.ApplicationPO._persistence_isAttributeFetched(ApplicationPO.java)
~[na:na]
	at
org.eclipse.jubula.client.core.persistence.locking.ApplicationPO._persistence_checkFetched(ApplicationPO.java)
~[na:na]
	at
org.eclipse.jubula.client.core.persistence.locking.ApplicationPO.getId(ApplicationPO.java)
~[na:na]
	... 18 common frames omitted
----------------------------------------------------------------------